### ISSUE TITLE
[BUG] -  1.20.4 not working

### ISSUE THREAD

**Issue by Pro245Mc** [XxDaShTixX/Minecraft-ArrowTNT#1]
Hi, been using this for quite some time. Great plugin, but the latest version won't work for me.
**Describe the bug**
1.20.4 paper
arrowtnt 1.5
Running with Java 17 

............................................................................................................
01.07 10:17:54 [Server] [ERROR] [ModernPluginLoadingStrategy] Could not load plugin 'ArrowTNT.jar' in folder 'plugins'
01.07 10:17:54 [Server] [INFO] org.bukkit.plugin.InvalidPluginException: Unsupported API version 1.20.6
01.07 10:17:54 [Server] [INFO] at org.bukkit.craftbukkit.v1_20_R3.util.CraftMagicNumbers.checkSupported(CraftMagicNumbers.java:389) ~[paper-1.20.4.jar:git-Paper-"f4c7d37"]
01.07 10:17:54 [Server] [INFO] at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:119) ~[paper-1.20.4.jar:git-Paper-"f4c7d37"]
01.07 10:17:54 [Server] [INFO] at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:35) ~[paper-1.20.4.jar:git-Paper-"f4c7d37"]
01.07 10:17:54 [Server] [INFO] at io.papermc.paper.plugin.entrypoint.strategy.modern.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:116) ~[paper-1.20.4.jar:git-Paper-"f4c7d37"]
01.07 10:17:54 [Server] [INFO] at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:38) ~[paper-1.20.4.jar:git-Paper-"f4c7d37"]
01.07 10:17:54 [Server] [INFO] at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[paper-1.20.4.jar:git-Paper-"f4c7d37"]
01.07 10:17:54 [Server] [INFO] at org.bukkit.craftbukkit.v1_20_R3.CraftServer.loadPlugins(CraftServer.java:507) ~[paper-1.20.4.jar:git-Paper-"f4c7d37"]
01.07 10:17:54 [Server] [INFO] at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:274) ~[paper-1.20.4.jar:git-Paper-"f4c7d37"]
01.07 10:17:54 [Server] [INFO] at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1131) ~[paper-1.20.4.jar:git-Paper-"f4c7d37"]
01.07 10:17:54 [Server] [INFO] at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-"f4c7d37"]
01.07 10:17:54 [Server] [INFO] at java.lang.Thread.run(Thread.java:833) ~[?:?]
01.07 10:17:54 [Server] [WARN] [org.bukkit.craftbukkit.v1_20_R3.legacy.CraftLegacy] Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!

**Comment by XxDaShTixX** [comment]
Hi @Pro245Mc ,
Thanks for reporting this issue. 
It looks like the target API wasn't targeting all 1.20.x versions of Minecraft. 
This should be fixed now. Please check the new [ArrowTNT v1.5.1](https://github.com/XxDaShTixX/Minecraft-ArrowTNT/releases/tag/v1.5.1) release which should now work with v1.20.x
Fixed with commit #2

**Comment by Pro245Mc** [comment]
Thanks you so much for the fast fix. Amazing timing. Its loads correctly.

Oh wait, it seem to be working, sorry. 

I have a different bug. 

I have 2 worlds. In my main world, the explosion is very small visually, and does not destroy blocks, which is good. But in the second world, it destroys the blocks and the explosion is bigger? Normally its shouldn't destroy the blocks, and In my main world, the explosion stays very small, even if I change the explosion value. Nothing to do with world guard by the way.

I tried to look into the conf, but nothing changed.

Ps, could you make the enabled and disable messages, coloured like before? green for on Red for off?
Thanks soooo much for this

**Comment by XxDaShTixX** [comment]
@Pro245Mc Thanks for confirming that the plugin is loading correctly.

**Comment by Pro245Mc** [comment]
I edited the other comment, as I had a bug after. :)

**Comment by XxDaShTixX** [comment]
@Pro245Mc We can break these two requests down to 
1. A bug: Can you please submit a new issue for the explode issue per world? I would need to know how I can replicate the issue on my end. Please provide as much info as possible for me to replicate the exact environment that you have.
2. A feature: I have created a [feature request](https://github.com/XxDaShTixX/Minecraft-ArrowTNT/issues/3) that you can follow up with to know of its status.

**Comment by Pro245Mc** [comment]
Ok I will do that's. Thanks
